### ISSUE TITLE
What's hpdf?

### ISSUE THREAD

**Issue by nigelhorne** [billthefarmer/gpdf#1]
```
$ make
gcc -o gpdf gpdf.c -g -W -Wall -std=gnu99 -Iinclude -lhpdf
/usr/bin/ld: cannot find -lhpdf
collect2: error: ld returned 1 exit status
make: *** [Makefile:31: gpdf] Error 1
```

"apt install libhpdf" matched nothing.

**Comment by billthefarmer** [comment]
It's in the README...

>  [libHaru ](http://libharu.org) was used to produce the pdf
output. This will build successfully after the build files are
patched. The program is written in generic C, so should work on any
platform that libHaru will build on. To build libHaru on windows
requires zlib and libpng, which can be found in MingW32. To build
libHaru on Mac OSX requires libpng, which can be built and
installed. On Linux, just install zlib and libpng if they are not
already installed. On Linux Mint thats:
```
$ sudo apt install libz-dev libpng-dev
```
