### ISSUE TITLE
Doesn't support 8x11 paper size

### ISSUE THREAD

**Issue by nigelhorne** [billthefarmer/gpdf#4]
$subject

**Comment by billthefarmer** [comment]
You won't get much on a piece of paper that size. This is European software written in what was a European country until yesterday using metric dimensions, except for points. Easy enough to add any size paper you like, change the table on line 36:
```c
static const int pagesizes[5][2] =
    {{840, 1188},
     {594, 840},
     {420, 594},
     {297, 420},
     {210, 297}};
```
You could change the last entry for A4, or add an entry. If you add an entry you will need to update the switch statement on line 117:
```c
	case 'p':
	    if ((tolower(optarg[0]) == 'a') &&
		(atoi(&optarg[1]) >= 0) && (atoi(&optarg[1]) <= 4))
		pagesize = atoi(&optarg[1]);

	    else
	    {
		fprintf (stderr, "%s: '%s' is not a valid page size\n",
			 progname, optarg);
		return GPDF_ERROR;
	    }
	    break;
```
